project_id = "oknjfjplseopgymijnca"

[functions.peek-import-csv]
verify_jwt = false

[functions.lgo-delivery-webhook]
verify_jwt = false

[functions.notify-form-error]
verify_jwt = false

[functions.send-monthly-recap]
verify_jwt = false
