UPDATE produits_complementaires SET phrase_conseil = sub.phrase
FROM (VALUES
('1fc6f25b-8549-45ed-8d45-126afe8a4e5a'::uuid, 'Une crème solaire non comédogène prévient l''obstruction des pores, évitant l''aggravation des lésions acnéiques sous l''exposition solaire.'),
('f7743075-19dd-4254-aae6-154b85b47e92'::uuid, 'L''acné est souvent liée à une production excessive de sébum et une inflammation cutanée, le zinc aide à réguler le sébum et calmer la peau.'),
('095a525f-50d8-49d5-9ecc-3417856fca4a'::uuid, 'L''excès de sébum et l''obstruction des pores favorisent l''acné, un gel nettoyant purifiant régule le sébum et nettoie la peau en profondeur.'),
('94dcc7ef-2d0e-4350-a9ae-9a56aa9200bc'::uuid, 'L''allaitement peut épuiser les réserves maternelles, ces compléments soutiennent les besoins nutritionnels spécifiques du post-partum et l''énergie.'),
('62f61864-875f-41e0-a394-9d8c48f81eed'::uuid, 'L''allaitement peut causer des irritations et crevasses, la lanoline hydrate et protège la peau délicate des mamelons pour la cicatrisation.'),
('2e1448d2-b4ee-40fd-9e20-f487f1e99afd'::uuid, 'Certaines plantes, comme le fenouil, peuvent naturellement stimuler la production de lait maternel en agissant sur les hormones de lactation.'),
('50744c1d-68ea-473f-91b5-f9fe3660d1f7'::uuid, 'Une allergie alimentaire déclenche une réaction inflammatoire, un antihistaminique bloque cette réponse pour réduire les symptômes cutanés ou digestifs.'),
('f2d5008a-eff6-49c3-aeaa-13a589eac88a'::uuid, 'Une flore intestinale déséquilibrée peut amplifier les réactions allergiques, les probiotiques modulent cette flore pour réduire la sensibilité.'),
('66262ab8-26a4-4889-8c98-f14d46f08227'::uuid, 'Les réactions allergiques provoquent souvent des démangeaisons intenses, cette crème agit sur les médiateurs cutanés pour apaiser la sensation de prurit.'),
('9130ca55-f947-4de2-9669-c676ee9b5cb2'::uuid, 'L''allergie saisonnière irrite les yeux et provoque des démangeaisons, ce collyre stabilise les mastocytes pour soulager le prurit et le larmoiement.'),
('101d87c0-33df-46d2-8efa-3faff25638db'::uuid, 'Les allergènes provoquent une inflammation nasale, ce spray réduit la libération d''histamine pour décongestionner et calmer l''irritation des muqueuses.'),
('86d838a2-b101-4afd-9d2d-54ba87f49403'::uuid, 'Les allergies déclenchent une libération d''histamine, ce collyre antihistaminique bloque la réponse immunitaire pour calmer les démangeaisons oculaires.'),
('8a4fd92f-91c2-49f4-adcd-fd919d4b1591'::uuid, 'L''anémie ferriprive est due à un manque de fer, ces gélules de fer bisglycinate compensent le déficit pour restaurer les réserves de l''organisme.'),
('87b90540-8cd6-404e-83e6-c8cbbb8649e8'::uuid, 'Le manque de fer cause l''anémie, le fer bisglycinate est bien absorbé et mieux toléré pour reconstituer efficacement les réserves en fer.'),
('ffd62472-9519-405f-a71e-efb8929161d0'::uuid, 'L''absorption du fer est souvent limitée, la vitamine C optimise cette absorption au niveau intestinal, améliorant ainsi la correction de l''anémie.'),
('2300ca55-f783-4add-aedf-9a0fd4464f97'::uuid, 'L''angine cause une inflammation et une infection de la gorge, ce collutoire agit localement pour calmer la douleur et réduire la prolifération microbienne.'),
('a819ad76-1f85-45d3-9dce-91652b51c51a'::uuid, 'Une angine provoque une inflammation douloureuse de la gorge, ces pastilles anesthésiantes agissent localement pour bloquer la transmission de la douleur.'),
('1adafd64-0e33-4173-a8af-261b8760d337'::uuid, 'L''angine est souvent associée à une infection de la gorge, la propolis forme une barrière protectrice pour apaiser et réduire l''inflammation locale.'),
('6965a35c-6e5e-4b31-ab0a-32772850ecae'::uuid, 'L''angor implique un stress sur le système cardiovasculaire, les oméga-3 aident à réduire l''inflammation et l''agrégation plaquettaire pour protéger le cœur.'),
('61e92ef5-ec69-4b24-9801-1e7b97c1f56e'::uuid, 'L''angor est lié à un manque d''oxygène au cœur, la Coenzyme Q10 est essentielle à la production d''énergie cellulaire et améliore la fonction cardiaque.'),
('b92dfe01-a008-4de8-a26d-cf5575081584'::uuid, 'L''angor peut être lié à un stress cardiovasculaire, le magnésium marin contribue à la relaxation musculaire et au maintien d''un rythme cardiaque normal.'),
('b71f8509-f79a-4dfa-9247-c1217f14c6a1'::uuid, 'Le stress et l''anxiété peuvent épuiser les réserves de magnésium, le magnésium marin et la vitamine B6 contribuent à un fonctionnement nerveux équilibré.'),
('19bff676-42b0-43d5-be10-e6b22e129883'::uuid, 'L''anxiété entraîne une hyperexcitabilité du système nerveux, le magnésium bisglycinate aide à réguler les neurotransmetteurs pour un effet calmant.'),
('bc85553b-f354-4229-bb8e-fa556ae047f3'::uuid, 'Le stress et l''anxiété peuvent perturber le système nerveux, le magnésium B6 contribue à sa régulation pour retrouver la sérénité.'),
('0b921067-8cfd-47b7-be4a-edaba23fcf85'::uuid, 'L''anxiété légère est souvent liée à un déséquilibre nerveux, le magnésium marin contribue à un fonctionnement normal du système nerveux pour apaiser.'),
('3c1465e2-4b9c-478b-9f22-afab264a905c'::uuid, 'L''anxiété légère cause une agitation nerveuse, la passiflore agit sur les récepteurs GABA pour calmer le système nerveux sans somnolence.'),
('e988854c-cf5f-4cf8-add2-bae2ad973899'::uuid, 'L''anxiété légère peut provoquer une tension nerveuse, l''huile essentielle de lavande vraie, par inhalation, régule le système nerveux pour une relaxation.'),
('b70b80c7-9ee9-4abe-9a82-6796c50fe440'::uuid, 'Les aphtes sont des lésions douloureuses de la muqueuse buccale, ce gel crée un film protecteur pour favoriser la cicatrisation et réduire la douleur.'),
('05f69b1a-e674-4448-a024-f1e1ff47e9e9'::uuid, 'Les aphtes sont des lésions buccales, un bain de bouche antiseptique réduit la charge bactérienne pour prévenir l''infection et accélérer la cicatrisation.'),
('f6f13410-ebf7-49bb-a3c3-f9fdb1fd2766'::uuid, 'Les aphtes peuvent s''infecter, le bicarbonate de soude aide à alcaliniser l''environnement buccal, créant un milieu moins propice aux bactéries et aidant à la guérison.'),
('ebef1c7a-209e-4214-baab-922f0c22cd8d'::uuid, 'L''arthrose implique une dégradation du cartilage articulaire, la glucosamine et la chondroïtine soutiennent sa régénération pour préserver la mobilité.'),
('358e54b2-e6df-49a6-a6e6-6df79b6722e4'::uuid, 'L''arthrose entraîne une instabilité et de la douleur articulaire, une genouillère stabilise l''articulation pour réduire les contraintes mécaniques.'),
('b3aa64d0-d05c-4fdd-8f55-c7ad1a50c146'::uuid, 'L''arthrose est caractérisée par la détérioration du cartilage, la chondroïtine et la glucosamine aident à le protéger et à ralentir sa dégradation.'),
('38dd2e09-4c71-40b5-9c67-6caa2e1c40fd'::uuid, 'Lors de l''asthme, un aérosol doit atteindre les poumons, la chambre d''inhalation améliore la dispersion du médicament pour une meilleure efficacité thérapeutique.'),
('e36aa0ee-730a-4e0c-8e71-1c11bdf75ae7'::uuid, 'L''asthme peut être aggravé par l''encombrement nasal, le spray nasal hypertonique décongestionne la muqueuse en drainant l''excès d''eau pour faciliter la respiration.'),
('a3fc8808-66ba-4b0e-8739-b4579015f82e'::uuid, 'Un asthme nécessite une médication précise, la chambre d''inhalation assure une meilleure délivrance du médicament aux bronches pour optimiser le traitement.'),
('d95506ad-3b5c-456c-a9ad-07f782f9d5ec'::uuid, 'Les ballonnements sont causés par l''accumulation de gaz, le charbon végétal activé piège ces gaz dans l''intestin, réduisant la distension abdominale.'),
('ace92a79-83de-487d-8398-45f755663006'::uuid, 'Les ballonnements proviennent de gaz intestinaux, la siméticone disperse ces gaz pour faciliter leur élimination et soulager la sensation de ventre gonflé.'),
('cbf8c98a-b7e5-40de-9e48-f2a1b8191414'::uuid, 'Les ballonnements sont souvent liés à un déséquilibre de la flore intestinale, les probiotiques rééquilibrent cette flore pour moduler la production de gaz.'),
('7ae4b494-23ad-418b-8d6a-01a4ac4fdebb'::uuid, 'Les ballonnements résultent de gaz piégés dans l''intestin, le charbon végétal activé adsorbe ces gaz pour diminuer leur volume et la pression.'),
('1a2cb9e5-15f8-49fc-8c09-22a89db03b79'::uuid, 'Les ballonnements sont souvent dus à l''accumulation de gaz, le fenouil aide à les expulser et réduire cette sensation désagréable.'),
('240edcaa-527e-4eaa-9c6d-0c91c0cb733f'::uuid, 'Les gaz intestinaux sont liés à un déséquilibre de la flore, les probiotiques rétablissent cet équilibre pour une meilleure digestion.'),
('062c1ced-4be4-48e5-a3ab-9af46d788e1b'::uuid, 'La blépharite provoque une inflammation des paupières, les lingettes aident à nettoyer les sécrétions et apaiser cette irritation.'),
('ce88d09c-ccbc-4948-aba8-25ef02115830'::uuid, 'La blépharite génère des dépôts sur les paupières, Blephaclean nettoie en douceur pour prévenir l''inflammation et l''infection.'),
('2f4c49a4-4d60-4136-9bfc-92de004ccd92'::uuid, 'La blépharite obstrue les glandes de Meibomius, le masque chauffant aide à liquefier les sécrétions pour améliorer leur écoulement.'),
('a75ba062-12e0-4667-9581-7f07176d625a'::uuid, 'La BPCO entraîne un encombrement nasal, le spray hypertonique décongestionne les muqueuses par effet osmotique, facilitant la respiration.'),
('dcf73e55-1ea6-4050-91d3-3b5132927f2c'::uuid, 'Le tabagisme aggrave la BPCO, les substituts nicotiniques aident à réduire l''apport en substances toxiques pour préserver les poumons.'),
('872cbb3b-c6e6-436d-91a8-5d1c3b983045'::uuid, 'Une BPCO nécessite souvent des traitements inhalés, la chambre d''inhalation améliore le dépôt pulmonaire pour une meilleure efficacité.'),
('bec8d91c-b330-429d-8f92-b86728130064'::uuid, 'La bronchite aiguë s''accompagne de sécrétions bronchiques, ce sirop fluidifie le mucus pour faciliter l''expectoration et dégager les voies respiratoires.'),
('37adbcff-2e45-4b61-979a-9b40e1b6e8a6'::uuid, 'La bronchite aiguë entraîne une inflammation des bronches, ces pastilles au miel adoucissent la gorge et calment la toux irritative.')
) AS sub(id, phrase)
WHERE produits_complementaires.id = sub.id;